# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{win}
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["arvicco"]
  s.date = %q{2010-02-10}
  s.description = %q{A collection of Windows functions predefined for you using FFI}
  s.email = %q{arvitallian@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "features/step_definitions/win_steps.rb",
     "features/support/env.rb",
     "features/win.feature",
     "lib/win/extensions.rb",
     "lib/win/library.rb",
     "lib/win/window.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/test_apps/locknote/LockNote.exe",
     "spec/win/extensions_spec.rb",
     "spec/win/library_spec.rb",
     "spec/win/window_spec.rb",
     "win.gemspec"
  ]
  s.homepage = %q{http://github.com/arvicco/win}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{A collection of Windows functions predefined for you using FFI}
  s.test_files = [
    "spec/spec_helper.rb",
     "spec/win/extensions_spec.rb",
     "spec/win/library_spec.rb",
     "spec/win/window_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_development_dependency(%q<cucumber>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<cucumber>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<cucumber>, [">= 0"])
  end
end

